### ISSUE TITLE
install-reddit.sh: No such file or directory

### ISSUE THREAD

**Issue by fmondora** [reddit/reddit-vagrant#19]
While vagrant up
==> default: /tmp/vagrant-shell: line 17: //host/src/reddit/install-reddit.sh: No such file or directory

**Comment by thedannywahl** [comment]
install-reddit.sh is part of [reddit/reddit](https://github.com/reddit/reddit) which is obviously missing from the virtual machine.  For now you need to download/clone reddit to the vm and run install-reddit.sh manually

**Comment by derjogi** [comment]
You might have to change some more things in the Vagrantfile.
I had to change the single-quotes to double-quotes and replace +key with #{key} inside the quotes to make it mount correctly.
so it becomes
   config.vm.synced_folder value, "/host-raw/src/#{key}" [...]
   config.bindfs.bind_folder "/host-raw/src/#{key}", "/host/src/#{key}"

And then there are some other issues that might have popped up that I can't remember right now -.-

**Comment by derFunk** [comment]
+1
