### ISSUE TITLE
socket.timeout when creating the cassandra keyspace via install-reddit.sh

### ISSUE THREAD

**Issue by derFunk** [reddit/reddit-vagrant#22]
When executing `vagrant up` on reddit-vagrant, I'm getting a socket.timout when install-reddit.sh is creating the cassandra keyspace reproducibly:
`sys.create_keyspace("reddit", "SimpleStrategy", {"replication_factor": "1"})` -->  `socket.timeout: timed out`
(Context:  https://github.com/reddit/reddit/blob/master/install-reddit.sh#L248)

## Log:

> ==> default: ++ for plugin in '$REDDIT_PLUGINS'
> ==> default: ++ clone_reddit_plugin_repo liveupdate
> ==> default: ++ clone_reddit_repo liveupdate reddit/reddit-plugin-liveupdate
> ==> default: ++ local destination=/host/src/liveupdate
> ==> default: ++ local repository_url=https://github.com/reddit/reddit-plugin-liveupdate.git
> ==> default: ++ '[' '!' -d /host/src/liveupdate ']'
> ==> default: ++ sudo -u vagrant git clone https://github.com/reddit/reddit-plugin-liveupdate.git /host/src/liveupdate
> ==> default: Cloning into '/host/src/liveupdate'...
> ==> default: ++ '[' -d /host/src/liveupdate/upstart ']'
> ==> default: ++ cp /host/src/liveupdate/upstart/reddit-consumer-liveupdate_scraper_q.conf /host/src/liveupdate/upstart/reddit-job-> liveupdate_activity.conf /etc/init/
> ==> default: ++ python
> ==> default: creating keyspace 'reddit'
> ==> default: Traceback (most recent call last):
> ==> default:   File "<stdin>", line 6, in <module>
> ==> default:   File "/usr/lib/pymodules/python2.7/pycassa/system_manager.py", line 202, in create_keyspace
> ==> default:     self._system_add_keyspace(ksdef)
> ==> default:   File "/usr/lib/pymodules/python2.7/pycassa/system_manager.py", line 150, in _system_add_keyspace
> ==> default:     return self._schema_update(self._conn.system_add_keyspace, ksdef)
> ==> default:   File "/usr/lib/pymodules/python2.7/pycassa/system_manager.py", line 459, in _schema_update
> ==> default:     schema_version = schema_func(*args)
> ==> default:   File "/usr/lib/pymodules/python2.7/pycassa/cassandra/Cassandra.py", line 1646, in system_add_keyspace
> ==> default:     return self.recv_system_add_keyspace()
> ==> default:   File "/usr/lib/pymodules/python2.7/pycassa/cassandra/Cassandra.py", line 1657, in recv_system_add_keyspace
> ==> default:     (fname, mtype, rseqid) = self._iprot.readMessageBegin()
> ==> default:   File "/usr/lib/python2.7/dist-packages/thrift/protocol/TBinaryProtocol.py", line 126, in readMessageBegin
> ==> default:     sz = self.readI32()
> ==> default:   File "/usr/lib/python2.7/dist-packages/thrift/protocol/TBinaryProtocol.py", line 206, in readI32
> ==> default:     buff = self.trans.readAll(4)
> ==> default:   File "/usr/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 58, in readAll
> ==> default:     chunk = self.read(sz - have)
> ==> default:   File "/usr/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 271, in read
> ==> default:     self.readFrame()
> ==> default:   File "/usr/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 275, in readFrame
> ==> default:     buff = self.__trans.readAll(4)
> ==> default:   File "/usr/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 58, in readAll
> ==> default:     chunk = self.read(sz - have)
> ==> default:   File "/usr/lib/python2.7/dist-packages/thrift/transport/TSocket.py", line 103, in read
> ==> default:     buff = self.handle.recv(sz)
> ==> default: socket.timeout: timed out
> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.

![Colored log output screenshot](http://i.imgur.com/tM3kbz6.png)

(PS: When encountering the above I had to apply this patch manually: https://github.com/reddit/reddit-vagrant/pull/21 - this is now merged).

### Host info:
$ uname -a
Linux <hostname> 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ vagrant --version
Vagrant 1.7.2

**Comment by DorianGray** [comment]
Did you modify the memory settings or cpu in vagrant_config.yml? How much disk space do you have in the vm when this happens?

**Comment by DorianGray** [comment]
Also, virtualbox, vmware, or kvm?

**Comment by derFunk** [comment]
I'm running on VMWare ESXi in a VM with Virtual Hardware Version 10 (newest). Vagrant is generally working in this environment.

I have 7,1GiB free disk space on the host vm.

I did not change mem or cpu settings in the config file:
> # Specify which vagrant box to use.
> # VBox
> :box: "hashicorp/precise64"
> # KVM
> #:box: "KVM/precise64"
> #:box_url: "https://vagrant-kvm-boxes.s3.amazonaws.com/precise64-kvm.box"
> #VMWare
> #:box: "spantree/ubuntu-precise-64"
> 
> # Assign a private IP to your box.
> :private_ip: "192.168.150.2"
> # Force DHCP instead of static ip
> :dhcp: false
> # Give it a unique hostname(use a . to make cookies work)
> :hostname: reddit.local
> 
> # Expose the VM's port 80 on a specified port. May be set to false to disable.
> :forward_port: 8001
> 
> # Where, or if, the required repositories are located.
> # If any of these are set to false, they will be cloned
> # inside of the environment instead of mounted from outside.
> :local: {
> }
> # Specify what plugins to install here. If they are not also specified in local,
> # they must be found at https://github.com/reddit
> :plugins: [
>   "about",
>   "meatspace",
>   "liveupdate"
> ]
> # How much cpu and memory to use
> :cpu: 4 #Cores
> :memory: 4096 #MB
> #Use NFS for shared folder mounts(increases performance with virtualbox)
> :nfs: true

**Comment by derFunk** [comment]
@DorianGray you pointed me into the right direction by asking if I changed the config. I did not, but my VM was not configured correctly - I hadn't assigned 4 cores as the config states. 

After I did that cassandra booted up and reddit was installed. So this specific error is gone. Thanks.
